server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/, file:./src/main/resources/config-repo, file:../config-server/src/main/resources/config-repo, classpath:/config-repo
